http:
  port: 8081

page:
  title: "Panel View"
  footer: ""

generate-static-pages:
  export-dir: "export"

log:
  file: "./last.log"
  levels:
    errors: true
    warnings: true
    info: true
    debug: false
