const PG = require("../pagegen.js");

module.exports = {
    title: "Test JS Panel",
    drawContents: async () =>
    {
        return PG().p(
                PG("This is being generated by ")
                .i("Javascript")
                .append(".")
            );
    }
}
